Algoritmo "area-do-retangulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Vitório dos Santos
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
lado01: real
lado02: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um lado do retângulo: ")
leia(lado01)
escreval("Digite o lado adjascente ao anterior: ")
leia(lado02)

area <- lado01 * lado02

escreval("A área do seu retângulo é: ", area, " m²")

Fimalgoritmo