Algoritmo "maiorQue10"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Escreve se um valor é maior ou menor do que 10
// Autor(a)    : Gabriel Vitório dos Santos
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis 
valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor que você gostaria de comparar com 10:")
leia(valor)

se valor > 10 entao
escreva(valor, " é maior do que 10")
senao
escreva(valor, " é menor do que 10")
fimse

Fimalgoritmo