Algoritmo "max"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jail Costa dos Santos
// Descrição   : Escreve o maior entre 2 valores
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis 
valor02, valor01: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite dois valor para retornar o maior deles:")
leia(valor01)
leia(valor02)

se valor01 > valor02 entao
escreva("O maior valor é:", valor01)
senao
escreva("O maior valor é:", valor02)
fimse

Fimalgoritmo