Algoritmo "antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Vitório dos Santos
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01: inteiro
antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o número que você quer obter o antecessor: ")
leia(numero01)

antecessor <- numero01 - 1

escreval("O antecessor do seu número é: ", antecessor)

Fimalgoritmo